"""
Approach V2 Diagnostic Miss Analyzer
Analyzes all 1,165 missed ground-truth links from the 1,000-entity tuned blocking test.
Categorizes root causes into structural patterns (DBA/alias variances, heavy typos, token mismatch,
address discrepancies, cap truncation, and missing address fields).
"""

import csv
import sys
import time
import polars as pl
from collections import Counter, defaultdict
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

csv.field_size_limit(2147483647)

# Add approach root to sys.path
SRC_DIR = Path(__file__).resolve().parent
APPROACH_ROOT = SRC_DIR.parent
if str(APPROACH_ROOT) not in sys.path:
    sys.path.insert(0, str(APPROACH_ROOT))

from src.config import TRAIN_FILES, CANDIDATE_FILES
from src.build_indexes import (
    fast_normalize_name,
    fast_normalize_address,
    fast_normalize_country,
    extract_blocking_keys_fast_tuned
)


def analyze_misses():
    print("=" * 80)
    print("DIAGNOSTIC ANALYSIS OF THE 1,165 MISSED GROUND-TRUTH LINKS")
    print("=" * 80)
    t0 = time.time()

    cand_parquet = CANDIDATE_FILES["test_1k_candidates_tuned"]
    s1_tsv = TRAIN_FILES["s1"]
    s2_tsv = TRAIN_FILES["s2"]
    s3_tsv = TRAIN_FILES["s3"]
    gt_tsv = TRAIN_FILES["gt"]

    # 1. Load the 1,000 tested S1 entity IDs & raw attributes
    s1_data = {}
    s1_tested_ids = []
    with open(s1_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            s1_id = row["entity_id"].strip()
            s1_tested_ids.append(s1_id)
            s1_data[s1_id] = {
                "name_raw": row.get("business_name", ""),
                "addr_raw": row.get("business_address", ""),
                "country": row.get("country", ""),
                "name_norm": fast_normalize_name(row.get("business_name")),
                "addr_norm": fast_normalize_address(row.get("business_address")),
                "country_norm": fast_normalize_country(row.get("country"))
            }
            if len(s1_tested_ids) >= 1000:
                break

    set_s1_tested = set(s1_tested_ids)

    # 2. Load Ground Truth links for tested S1 entities
    gt_links = set()
    s1_gt_map = defaultdict(set)
    with open(gt_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            s1_id = row.get("source1_entity_id", "").strip()
            if s1_id in set_s1_tested:
                raw_matches = row.get("matched_entity_ids", "").strip()
                if raw_matches:
                    for m in raw_matches.split(","):
                        cand_id = m.strip()
                        if cand_id:
                            gt_links.add((s1_id, cand_id))
                            s1_gt_map[s1_id].add(cand_id)

    # 3. Load Candidates generated by tuned blocker
    df_cands = pl.read_parquet(cand_parquet)
    retrieved_links = set()
    for row in df_cands.iter_rows(named=True):
        s1_id = row["source1_entity_id"]
        cand_id = row["candidate_entity_id"]
        retrieved_links.add((s1_id, cand_id))

    # Identify exact missed pairs
    missed_pairs = gt_links - retrieved_links
    print(f"Total True Positive Links in Test Set: {len(gt_links):,}")
    print(f"Retrieved Links                      : {len(gt_links & retrieved_links):,}")
    print(f"Missed Links                         : {len(missed_pairs):,} ({round(len(missed_pairs)/len(gt_links)*100, 2)}%)")

    # Collect missed candidate entity IDs to fetch raw text from S2 / S3
    missed_s2_ids = {cand_id for s1_id, cand_id in missed_pairs if cand_id.startswith("S2-")}
    missed_s3_ids = {cand_id for s1_id, cand_id in missed_pairs if cand_id.startswith("S3-")}

    # Load S2/S3 text attributes for missed candidate IDs
    cand_data = {}

    if missed_s2_ids:
        with open(s2_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                cid = row.get("entity_id", "").strip()
                if cid in missed_s2_ids:
                    cand_data[cid] = {
                        "name_raw": row.get("business_name", ""),
                        "addr_raw": row.get("business_address", ""),
                        "country": row.get("country", ""),
                        "name_norm": fast_normalize_name(row.get("business_name")),
                        "addr_norm": fast_normalize_address(row.get("business_address")),
                        "country_norm": fast_normalize_country(row.get("country"))
                    }

    if missed_s3_ids:
        with open(s3_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                cid = row.get("entity_id", "").strip()
                if cid in missed_s3_ids:
                    cand_data[cid] = {
                        "name_raw": row.get("business_name", ""),
                        "addr_raw": row.get("business_address", ""),
                        "country": row.get("country", ""),
                        "name_norm": fast_normalize_name(row.get("business_name")),
                        "addr_norm": fast_normalize_address(row.get("business_address")),
                        "country_norm": fast_normalize_country(row.get("country"))
                    }

    # 4. Pattern Classification for the 1,165 Misses
    pattern_counts = Counter()
    pattern_examples = defaultdict(list)

    for s1_id, cand_id in missed_pairs:
        s1 = s1_data.get(s1_id, {})
        cand = cand_data.get(cand_id, {})

        if not s1 or not cand:
            pattern_counts["Missing Source Entity Row Data"] += 1
            continue

        s1_n = s1["name_norm"]
        cand_n = cand["name_norm"]
        s1_a = s1["addr_norm"]
        cand_a = cand["addr_norm"]

        s1_toks = set(s1_n.split()) if s1_n else set()
        cand_toks = set(cand_n.split()) if cand_n else set()
        shared_name_toks = {t for t in (s1_toks & cand_toks) if len(t) >= 3}

        s1_add_toks = set(s1_a.split()) if s1_a else set()
        cand_add_toks = set(cand_a.split()) if cand_a else set()
        shared_addr_toks = {t for t in (s1_add_toks & cand_add_toks) if len(t) >= 4}

        # Check key generation overlap
        s1_keys = extract_blocking_keys_fast_tuned(s1_n, s1_a, s1["country_norm"])
        cand_keys = extract_blocking_keys_fast_tuned(cand_n, cand_a, cand["country_norm"])

        s1_key_set = {(p, c, k) for p, c, k in s1_keys}
        cand_key_set = {(p, c, k) for p, c, k in cand_keys}

        shared_keys = s1_key_set & cand_key_set

        # Classification logic
        if shared_keys:
            p_type = "Truncated by Top-100 Candidate Cap per S1"
        elif s1["country_norm"] != cand["country_norm"]:
            p_type = "Country Categorical Mismatch"
        elif not s1_a or not cand_a:
            if not shared_name_toks and s1_n[:3] != cand_n[:3]:
                p_type = "Missing Address + Name Alias Variation (No Shared Key)"
            else:
                p_type = "Missing Address Field (No Address Keys)"
        elif not shared_name_toks and not shared_addr_toks and s1_n[:3] != cand_n[:3]:
            if abs(len(s1_n) - len(cand_n)) > 10 or (len(s1_toks) > 1 and len(cand_toks) > 1 and not (s1_toks & cand_toks)):
                p_type = "DBA / Acronym / Legal Name Alias Variance (Zero Token Overlap)"
            else:
                p_type = "Heavy Spelling Typo & Character Variation"
        elif shared_name_toks and not shared_keys:
            p_type = "Name Token Filtered by Stop Words or Frequency Cap (>500)"
        elif shared_addr_toks and not shared_keys:
            p_type = "Address Token Filtered by Stop Words or Frequency Cap (>500)"
        else:
            p_type = "Prefix & N-Gram Key Mismatch"

        pattern_counts[p_type] += 1
        if len(pattern_examples[p_type]) < 3:
            pattern_examples[p_type].append({
                "s1_id": s1_id,
                "cand_id": cand_id,
                "s1_name": s1["name_raw"],
                "cand_name": cand["name_raw"],
                "s1_address": s1["addr_raw"],
                "cand_address": cand["addr_raw"]
            })

    t_elapsed = round(time.time() - t0, 2)

    # 5. Print Results & Breakdown
    print("\n" + "=" * 80)
    print(f"ROOT CAUSE PATTERN BREAKDOWN FOR THE {len(missed_pairs):,} MISSED LINKS")
    print("=" * 80)

    for p_type, cnt in pattern_counts.most_common():
        pct = round(cnt / len(missed_pairs) * 100, 2)
        print(f"\n[Pattern] {p_type}")
        print(f"   Count  : {cnt:,} misses ({pct}%)")
        print("   Real Data Examples:")
        for ex in pattern_examples[p_type]:
            print(f"     * S1 [{ex['s1_id']}] : Name='{ex['s1_name']}' | Addr='{ex['s1_address']}'")
            print(f"       Cand [{ex['cand_id']}]: Name='{ex['cand_name']}' | Addr='{ex['cand_address']}'")

    print("\n" + "=" * 80)
    print(f"Analysis completed in {t_elapsed}s.")
    print("=" * 80)


if __name__ == "__main__":
    analyze_misses()
