"""
Approach V2 Full-Scale Candidate Recall Evaluator
Evaluates candidate recall across all 2,206,821 Source-1 entities against train_ground_truth.tsv.
Uses memory-efficient Polars fast multithreaded engine.
Performs root cause categorization on missed ground-truth links.
Saves reports to experiments/candidate_recall_full.json and candidate_recall_full.txt.
"""

import csv
import json
import re
import sys
import time
import sqlite3
import argparse
import unicodedata
import polars as pl
from collections import defaultdict
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

csv.field_size_limit(2147483647)

# Add approach root to sys.path
SRC_DIR = Path(__file__).resolve().parent
APPROACH_ROOT = SRC_DIR.parent
if str(APPROACH_ROOT) not in sys.path:
    sys.path.insert(0, str(APPROACH_ROOT))

from src.config import TRAIN_FILES, CANDIDATE_FILES, INDEX_TUNED_DB_PATH, EXPERIMENTS_DIR
from src.build_indexes import (
    fast_normalize_name,
    fast_normalize_address,
    fast_normalize_country,
    extract_blocking_keys_fast_tuned
)

RE_NON_ASCII = re.compile(r"[^\x00-\x7F]")


def analyze_missed_link_category(
    s1_id: str,
    missed_cand_id: str,
    s1_text_map: dict,
    cur: sqlite3.Cursor
) -> str:
    """
    Determines root cause category for a missed ground truth link (s1_id -> missed_cand_id).
    Categories:
    1. generated but removed by top-100 ranking/cap
    2. never generated by blocking
    3. normalization/abbreviation
    4. address variation
    5. multilingual/script mismatch
    6. other
    """
    s1_n, s1_a, s1_c = s1_text_map.get(s1_id, ("", "", ""))

    # Fetch candidate text from entity_text table in SQLite
    cur.execute("SELECT name_norm, addr_norm FROM entity_text WHERE entity_id = ?;", (missed_cand_id,))
    cand_row = cur.fetchone()
    cand_n = cand_row[0] if cand_row else ""
    cand_a = cand_row[1] if cand_row else ""

    # Check 1: Was candidate generated by blocking (present in SQLite inverted_index under s1's keys)?
    keys = extract_blocking_keys_fast_tuned(s1_n, s1_a, s1_c)
    if keys:
        placeholders = ",".join(["(?,?)"] * len(keys))
        query = f"SELECT 1 FROM inverted_index WHERE country = ? AND entity_id = ? AND (pass_id, block_key) IN ({placeholders}) LIMIT 1;"
        params = [s1_c, missed_cand_id]
        for p_id, ctry, b_key in keys:
            params.extend([p_id, b_key])
        cur.execute(query, params)
        if cur.fetchone():
            return "1. generated but removed by top-100 ranking/cap"

    # Check 5: Multilingual / script mismatch
    if RE_NON_ASCII.search(s1_n) or RE_NON_ASCII.search(cand_n) or RE_NON_ASCII.search(s1_a) or RE_NON_ASCII.search(cand_a):
        return "5. multilingual/script mismatch"

    # Check 3: Normalization / abbreviation mismatch
    s1_ntoks = set(s1_n.split())
    cand_ntoks = set(cand_n.split())
    if s1_ntoks and cand_ntoks:
        # Check prefix or partial substring matches among tokens
        common_stems = sum(1 for t1 in s1_ntoks for t2 in cand_ntoks if (t1.startswith(t2[:4]) or t2.startswith(t1[:4])) and len(t1) >= 4 and len(t2) >= 4)
        if common_stems > 0:
            return "3. normalization/abbreviation"

    # Check 4: Address variation
    s1_atoks = set(s1_a.split())
    cand_atoks = set(cand_a.split())
    if not s1_a or not cand_a or len(s1_atoks & cand_atoks) == 0:
        return "4. address variation"

    # Category 2: Never generated by blocking
    return "2. never generated by blocking"


def evaluate_full_candidate_recall(sample_analysis_limit: int = 100_000):
    print("=" * 80)
    print("APPROACH V2: FULL CANDIDATE RECALL EVALUATION (2.2M S1 ENTITIES)")
    print("=" * 80)
    t0 = time.time()

    cand_parquet = CANDIDATE_FILES["train_candidates"]
    gt_tsv = TRAIN_FILES["gt"]
    s1_tsv = TRAIN_FILES["s1"]

    if not cand_parquet.exists():
        raise FileNotFoundError(f"Candidate parquet not found at {cand_parquet}")
    if not gt_tsv.exists():
        raise FileNotFoundError(f"Ground truth file not found at {gt_tsv}")

    # Step 1: Load Ground Truth for ALL S1 entities
    print("Loading Ground Truth labels from train_ground_truth.tsv...", flush=True)
    t_gt = time.time()
    gt_map = {}
    gt_rows = []
    total_gt_links = 0
    total_s1_eval = 0

    with open(gt_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            s1_id = row.get("source1_entity_id", "").strip()
            if not s1_id:
                continue
            total_s1_eval += 1
            raw_matches = row.get("matched_entity_ids", "").strip()
            if raw_matches:
                matches = {m.strip() for m in raw_matches.split(",") if m.strip()}
                gt_map[s1_id] = matches
                total_gt_links += len(matches)
                for m in matches:
                    gt_rows.append((s1_id, m))
            else:
                gt_map[s1_id] = set()

    df_gt = pl.DataFrame(gt_rows, schema=[("source1_entity_id", pl.Utf8), ("candidate_entity_id", pl.Utf8)], orient="row")
    print(f"  [DONE] Loaded GT for {total_s1_eval:,} S1 entities ({total_gt_links:,} positive GT links) in {round(time.time() - t_gt, 2)}s", flush=True)

    # Step 2: Use Polars for ultra-fast candidate scan & inner join
    print(f"\nScanning {cand_parquet.name} with Polars fast multithreaded engine...", flush=True)
    t_scan = time.time()

    lf_cand = pl.scan_parquet(cand_parquet)

    # Candidate counts per S1 entity
    cand_counts_df = lf_cand.group_by("source1_entity_id").agg(pl.len().alias("n_cands")).collect()
    cand_count_map = dict(zip(cand_counts_df["source1_entity_id"].to_list(), cand_counts_df["n_cands"].to_list()))
    del cand_counts_df

    # Inner join to find retrieved GT links
    retrieved_df = lf_cand.join(df_gt.lazy(), on=["source1_entity_id", "candidate_entity_id"], how="inner").collect()
    
    # Store retrieved pairs for each S1
    retrieved_gt_set_per_s1 = defaultdict(set)
    for s1_id, cand_id in zip(retrieved_df["source1_entity_id"], retrieved_df["candidate_entity_id"]):
        retrieved_gt_set_per_s1[s1_id].add(cand_id)

    total_gt_retrieved = len(retrieved_df)
    print(f"  [DONE] Retrieved {total_gt_retrieved:,} / {total_gt_links:,} GT links in {round(time.time() - t_scan, 2)}s", flush=True)

    # Step 3: Compute Overall & Entity-Level Recall Metrics
    print("\nComputing overall & entity-level recall metrics...", flush=True)
    
    zero_gt_s1_count = 0
    complete_recall_s1_count = 0
    partial_recall_s1_count = 0
    zero_recall_s1_count = 0
    zero_candidate_s1_count = 0

    missed_gt_pairs = []

    for s1_id, true_set in gt_map.items():
        n_true = len(true_set)
        n_cands = cand_count_map.get(s1_id, 0)

        if n_cands == 0:
            zero_candidate_s1_count += 1

        if n_true == 0:
            zero_gt_s1_count += 1
            continue

        retrieved_set = retrieved_gt_set_per_s1.get(s1_id, set())
        n_retrieved = len(retrieved_set)

        missed_set = true_set - retrieved_set
        for m_id in missed_set:
            missed_gt_pairs.append((s1_id, m_id))

        if n_retrieved == n_true:
            complete_recall_s1_count += 1
        elif n_retrieved > 0:
            partial_recall_s1_count += 1
        else:
            zero_recall_s1_count += 1

    active_s1_count = total_s1_eval - zero_gt_s1_count
    missed_gt_links = total_gt_links - total_gt_retrieved
    overall_recall_pct = round(total_gt_retrieved / total_gt_links * 100, 2) if total_gt_links > 0 else 0.0

    complete_recall_pct = round(complete_recall_s1_count / active_s1_count * 100, 2)
    partial_recall_pct = round(partial_recall_s1_count / active_s1_count * 100, 2)
    zero_recall_pct = round(zero_recall_s1_count / active_s1_count * 100, 2)
    zero_candidate_pct = round(zero_candidate_s1_count / total_s1_eval * 100, 2)

    # Step 4: Root Cause Breakdown Analysis of Missed Links
    print(f"\nAnalyzing root causes for {len(missed_gt_pairs):,} missed ground-truth links...", flush=True)
    t_missed = time.time()

    print("  Loading S1 normalized attributes for missed link analysis...", flush=True)
    s1_text_map = {}
    with open(s1_tsv, mode="r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            s1_id = row.get("entity_id", "").strip()
            if s1_id:
                s1_text_map[s1_id] = (
                    fast_normalize_name(row.get("business_name")),
                    fast_normalize_address(row.get("business_address")),
                    fast_normalize_country(row.get("country"))
                )

    conn = sqlite3.connect(f"file:{INDEX_TUNED_DB_PATH.resolve().as_posix()}?mode=ro", uri=True)
    cur = conn.cursor()

    category_counts = defaultdict(int)

    analysis_sample = missed_gt_pairs[:sample_analysis_limit] if len(missed_gt_pairs) > sample_analysis_limit else missed_gt_pairs
    sample_size = len(analysis_sample)

    for idx, (s1_id, missed_cand_id) in enumerate(analysis_sample, 1):
        cat = analyze_missed_link_category(s1_id, missed_cand_id, s1_text_map, cur)
        category_counts[cat] += 1

        if idx % 25_000 == 0:
            print(f"    Analyzed {idx:,} / {sample_size:,} missed links...", flush=True)

    conn.close()

    scale_factor = len(missed_gt_pairs) / sample_size if sample_size > 0 else 1.0
    scaled_category_counts = {cat: round(cnt * scale_factor) for cat, cnt in category_counts.items()}
    category_pcts = {cat: round(cnt / sample_size * 100, 2) if sample_size > 0 else 0.0 for cat, cnt in category_counts.items()}

    t_total = round(time.time() - t0, 2)

    # Step 5: Save JSON & TXT Reports
    json_results = {
        "summary": {
            "total_s1_entities_evaluated": total_s1_eval,
            "s1_entities_with_zero_gt_matches": zero_gt_s1_count,
            "s1_entities_with_active_gt_matches": active_s1_count,
            "total_ground_truth_links": total_gt_links,
            "retrieved_ground_truth_links": total_gt_retrieved,
            "missed_ground_truth_links": missed_gt_links,
            "overall_candidate_recall_pct": overall_recall_pct,
            "complete_recall_s1_count": complete_recall_s1_count,
            "complete_recall_s1_pct": complete_recall_pct,
            "partial_recall_s1_count": partial_recall_s1_count,
            "partial_recall_s1_pct": partial_recall_pct,
            "zero_recall_s1_count": zero_recall_s1_count,
            "zero_recall_s1_pct": zero_recall_pct,
            "zero_candidate_s1_count": zero_candidate_s1_count,
            "zero_candidate_s1_pct": zero_candidate_pct
        },
        "missed_links_root_cause_breakdown": {
            cat: {
                "sample_count": category_counts[cat],
                "estimated_total_count": scaled_category_counts[cat],
                "percentage": category_pcts[cat]
            }
            for cat in sorted(category_counts.keys())
        }
    }

    out_json = EXPERIMENTS_DIR / "candidate_recall_full.json"
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(json_results, f, indent=2)

    out_txt = EXPERIMENTS_DIR / "candidate_recall_full.txt"
    with open(out_txt, "w", encoding="utf-8") as f:
        f.write("=" * 80 + "\n")
        f.write("APPROACH V2: FULL CANDIDATE RECALL EVALUATION REPORT (2.2M S1 ENTITIES)\n")
        f.write("=" * 80 + "\n\n")

        f.write("1. PRIMARY CANDIDATE RECALL METRICS:\n")
        f.write(f"  - Total Ground-Truth Links             : {total_gt_links:,}\n")
        f.write(f"  - Retrieved Ground-Truth Links         : {total_gt_retrieved:,}\n")
        f.write(f"  - MISSED Ground-Truth Links            : {missed_gt_links:,}\n")
        f.write(f"  - OVERALL CANDIDATE RECALL %           : {overall_recall_pct}%\n\n")

        f.write("2. ENTITY-LEVEL RECALL BREAKDOWN:\n")
        f.write(f"  - Complete-Recall S1 % (All GT retrieved): {complete_recall_pct}% ({complete_recall_s1_count:,} entities)\n")
        f.write(f"  - Partial-Recall S1 %                   : {partial_recall_pct}% ({partial_recall_s1_count:,} entities)\n")
        f.write(f"  - Zero-Recall S1 %                      : {zero_recall_pct}% ({zero_recall_s1_count:,} entities)\n")
        f.write(f"  - Zero-Candidate S1 %                   : {zero_candidate_pct}% ({zero_candidate_s1_count:,} entities)\n\n")

        f.write("3. MISSED LINKS ROOT CAUSE BREAKDOWN:\n")
        for cat in sorted(category_counts.keys()):
            f.write(f"  - {cat:45s} : {scaled_category_counts[cat]:,} links ({category_pcts[cat]}%)\n")
        f.write("\n" + "=" * 80 + "\n")

    # Step 6: Print Exact Formatted Summary to Terminal
    print("\n" + "=" * 80)
    print("APPROACH V2: FULL CANDIDATE RECALL EVALUATION SUMMARY")
    print("=" * 80)
    print(f"Total Ground-Truth Links      : {total_gt_links:,}")
    print(f"Retrieved Ground-Truth Links  : {total_gt_retrieved:,}")
    print(f"MISSED Ground-Truth Links     : {missed_gt_links:,}")
    print(f"OVERALL CANDIDATE RECALL %    : {overall_recall_pct}%")
    print("-" * 60)
    print(f"Complete-Recall S1 %          : {complete_recall_pct}% ({complete_recall_s1_count:,} entities)")
    print(f"Partial-Recall S1 %           : {partial_recall_pct}% ({partial_recall_s1_count:,} entities)")
    print(f"Zero-Recall S1 %              : {zero_recall_pct}% ({zero_recall_s1_count:,} entities)")
    print(f"Zero-Candidate S1 %           : {zero_candidate_pct}% ({zero_candidate_s1_count:,} entities)")
    print("-" * 60)
    print("MISSED LINKS ROOT CAUSE BREAKDOWN:")
    for cat in sorted(category_counts.keys()):
        print(f"  - {cat:45s} : {scaled_category_counts[cat]:,} links ({category_pcts[cat]}%)")
    print("-" * 60)
    print(f"Saved JSON report to           : {out_json.name}")
    print(f"Saved TXT report to            : {out_txt.name}")
    print(f"Total Execution Time           : {t_total}s ({round(t_total/60, 2)} minutes)")
    print("=" * 80)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-limit", type=int, default=100000, help="Sample size for missed link root cause analysis")
    args = parser.parse_args()

    evaluate_full_candidate_recall(sample_analysis_limit=args.sample_limit)


if __name__ == "__main__":
    main()
